### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by krrishdholakia** [streamlit/llm-examples#18]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/streamlit/llm-examples/blob/7e97a0e5e543cc29df71c6c664f76aeadeab4850/pages/1_File_Q%26A.py#L25

Would love to know if this might help - https://github.com/BerriAI/litellm

~100 lines of code, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by krrishdholakia** [comment]
cc: @jeffkayne

**Comment by sfc-gh-jcarroll** [comment]
Thanks! I don't think we will add this dependency as the point of the app is to show the simple version that calls anthropic directly. The app seems to be working now from what I can tell.
